// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUaoi_VbW2Sj3qMABvwmQUkZ-4JoIqLG4',
    appId: '1:744768640367:web:c36e78b6d43d722d9b849a',
    messagingSenderId: '744768640367',
    projectId: 'voicebridge-e6336',
    authDomain: 'voicebridge-e6336.firebaseapp.com',
    storageBucket: 'voicebridge-e6336.firebasestorage.app',
    measurementId: 'G-S25LJ5CYJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKGaLEe06wJbiPXFDqpTjxsTDD-y5SMnI',
    appId: '1:744768640367:android:512243ad26bbf1219b849a',
    messagingSenderId: '744768640367',
    projectId: 'voicebridge-e6336',
    storageBucket: 'voicebridge-e6336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ZkJ4cfxWNQKYQtjIY3uFt6ksxwsuIw4',
    appId: '1:744768640367:ios:46decc2e55ef60df9b849a',
    messagingSenderId: '744768640367',
    projectId: 'voicebridge-e6336',
    storageBucket: 'voicebridge-e6336.firebasestorage.app',
    iosBundleId: 'com.example.voicebridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ZkJ4cfxWNQKYQtjIY3uFt6ksxwsuIw4',
    appId: '1:744768640367:ios:46decc2e55ef60df9b849a',
    messagingSenderId: '744768640367',
    projectId: 'voicebridge-e6336',
    storageBucket: 'voicebridge-e6336.firebasestorage.app',
    iosBundleId: 'com.example.voicebridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUaoi_VbW2Sj3qMABvwmQUkZ-4JoIqLG4',
    appId: '1:744768640367:web:c3a98a37a0d8a2c49b849a',
    messagingSenderId: '744768640367',
    projectId: 'voicebridge-e6336',
    authDomain: 'voicebridge-e6336.firebaseapp.com',
    storageBucket: 'voicebridge-e6336.firebasestorage.app',
    measurementId: 'G-3N8SQK1PGB',
  );
}
